/* $Id: BuiltInName.h,v 1.2 2002-08-25 15:30:09 pgr Exp $ */

#ifndef BUILTINNAME_HEADER
#define BUILTINNAME_HEADER

/*---------+
| Includes |
+---------*/
#include "resgendef.h"

/*------------------------------------------------------------ BuiltInNameId -+
|                                                                             |
+----------------------------------------------------------------------------*/
enum BuiltInNameId {
   _BLTIN__ABBREV,
   _BLTIN__ABS,
   _BLTIN__ACOS,
   _BLTIN__ADDRESS,
   _BLTIN__ARG,
   _BLTIN__ASIN,
   _BLTIN__ATAN,
   _BLTIN__ATAN2,
   _BLTIN__B2X,
   _BLTIN__BITAND,
   _BLTIN__BITOR,
   _BLTIN__BITXOR,
   _BLTIN__C2D,
   _BLTIN__C2X,
   _BLTIN__CENTER,
   _BLTIN__CENTRE,
   _BLTIN__CHANGESTR,
   _BLTIN__CHARIN,
   _BLTIN__CHAROUT,
   _BLTIN__CHARS,
   _BLTIN__COMPARE,
   _BLTIN__COPIES,
   _BLTIN__COS,
   _BLTIN__COSH,
   _BLTIN__COUNTSTR,
   _BLTIN__D2C,
   _BLTIN__D2X,
   _BLTIN__DATATYPE,
   _BLTIN__DATE,
   _BLTIN__DELSTR,
   _BLTIN__DELWORD,
   _BLTIN__DESBUF,
   _BLTIN__DIGITS,
   _BLTIN__DROPBUF,
   _BLTIN__ERRORTEXT,
   _BLTIN__EXP,
   _BLTIN__FORM,
   _BLTIN__FORMAT,
   _BLTIN__FUZZ,
   _BLTIN__INSERT,
   _BLTIN__LASTPOS,
   _BLTIN__LEFT,
   _BLTIN__LENGTH,
   _BLTIN__LINEIN,
   _BLTIN__LINEOUT,
   _BLTIN__LINES,
   _BLTIN__LOAD,
   _BLTIN__LOG,
   _BLTIN__LOG10,
   _BLTIN__MAKEBUF,
   _BLTIN__MAX,
   _BLTIN__MIN,
   _BLTIN__OVERLAY,
   _BLTIN__POS,
   _BLTIN__POW,
   _BLTIN__POW10,
   _BLTIN__QUEUED,
   _BLTIN__RANDOM,
   _BLTIN__REVERSE,
   _BLTIN__RIGHT,
   _BLTIN__SIGN,
   _BLTIN__SIN,
   _BLTIN__SINH,
   _BLTIN__SOURCELINE,
   _BLTIN__SPACE,
   _BLTIN__SQRT,
   _BLTIN__STREAM,
   _BLTIN__STRIP,
   _BLTIN__SUBSTR,
   _BLTIN__SUBWORD,
   _BLTIN__SYMBOL,
   _BLTIN__TAN,
   _BLTIN__TANH,
   _BLTIN__TIME,
   _BLTIN__TRACE,
   _BLTIN__TRANSLATE,
   _BLTIN__TRUNC,
   _BLTIN__VALUE,
   _BLTIN__VERIFY,
   _BLTIN__WORD,
   _BLTIN__WORDINDEX,
   _BLTIN__WORDLENGTH,
   _BLTIN__WORDPOS,
   _BLTIN__WORDS,
   _BLTIN__X2B,
   _BLTIN__X2C,
   _BLTIN__X2D,
   _BLTIN__XMLATTVAL,
   _BLTIN__XMLIN,
   _BLTIN__XMLOUT,
   _BLTIN__XMLTAGNAME,
   _BLTIN__XMLTYPE,
   _BLTIN__XRANGE,
   _BLTIN_NumberOf
};

RESOURCES_API char const * getBuiltInName(BuiltInNameId id);

#endif /* BUILTINNAME_HEADER ================================================*/
