//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 19:13:20  on Saturday, September 14, 2002
//
//	Generated for file: D:\u\newdev\yaxx\mwerks\tests\Rsc\tests.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"tests"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainConsoleField                          1001	//(Left Origin = 0, Top Origin = 20, Width = 150, Height = 140, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 10000, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainUnnamed1002GraffitiShift              1002	//(Left Origin = 149, Top Origin = 148)
#define MainConsoleScrollBar                      1003	//(Left Origin = 154, Top Origin = 20, Width = 6, Height = 140, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define SerialStartAlert                          1100
#define SerialStartOK                             0

//	Resource: Talt 1200
#define NetStartAlert                             1200
#define NetStartOK                                0

//	Resource: Talt 1500
#define NoServerAlert                             1500
#define NoServerOK                                0

//	Resource: Talt 3100
#define MessageBoxInfoAlert                       3100
#define MessageBoxInfoOK                          0


//	Resource: MBAR 1000
#define MainMenuBar                               1000


//	Resource: MENU 1000
#define MainMenu                                  1000
#define MainDbmByteStream                         1000
#define MainDbmRecStream                          1001
#define MainFileStream                            1002
#define MainSerial                                1003
#define MainNetTcpIP                              1004
#define MainBeamer                                1005
#define MainTime                                  1006


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

