//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 11:22:00 AM on Thursday, December 12, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Jaxo's Rexx"
//
//	Palm App Version:		"1.0.0"


//	Resource: tFRM 1000
#define EditForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1200, Default Button ID = 0)
#define EditRunWithArgsButton                     1002	//(Left Origin = 30, Top Origin = 145, Width = 26, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditRunButton                             1003	//(Left Origin = 3, Top Origin = 145, Width = 23, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditClearButton                           1004	//(Left Origin = 96, Top Origin = 145, Width = 26, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditDoneButton                            1005	//(Left Origin = 126, Top Origin = 145, Width = 24, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditLoadButton                            1007	//(Left Origin = 60, Top Origin = 145, Width = 32, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define EditInstructionsField                     1001	//(Left Origin = 0, Top Origin = 16, Width = 152, Height = 124, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 32767, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define EditNumberOfScriptsField                  1010	//(Left Origin = 81, Top Origin = 2, Width = 24, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 4, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define EditUnnamed1006GraffitiShift              1006	//(Left Origin = 152, Top Origin = 151)
#define EditNumberOfScriptsLabel                  1008	//(Left Origin = 107, Top Origin = 2, Usable = 1, Font = Standard)
#define EditInstructionsScrollBar                 1009	//(Left Origin = 153, Top Origin = 20, Width = 7, Height = 124, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1500
#define RexxletConsoleForm                        1500	//(Left Origin = 17, Top Origin = 33, Width = 126, Height = 106, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RexxletConsoleDoneButton                  1503	//(Left Origin = 82, Top Origin = 93, Width = 34, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletConsoleIOField                     1501	//(Left Origin = 1, Top Origin = 12, Width = 117, Height = 81, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 2000, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define RexxletConsoleReturnCodeField             1504	//(Left Origin = 2, Top Origin = 93, Width = 51, Height = 11, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 15, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RexxletConsoleIOScrollBar                 1502	//(Left Origin = 119, Top Origin = 14, Width = 7, Height = 79, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1400
#define LoaditForm                                1400	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define LoaditRunWithArgsButton                   1401	//(Left Origin = 30, Top Origin = 145, Width = 26, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LoaditRunButton                           1403	//(Left Origin = 3, Top Origin = 145, Width = 23, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LoaditDoneButton                          1405	//(Left Origin = 126, Top Origin = 145, Width = 24, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LoaditEditButton                          1409	//(Left Origin = 60, Top Origin = 145, Width = 32, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define LoaditNumberOfScriptsField                1407	//(Left Origin = 112, Top Origin = 2, Width = 24, Height = 13, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 4, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define LoaditUnnamed1408Label                    1408	//(Left Origin = 138, Top Origin = 2, Usable = 1, Font = Standard)
#define LoaditListScrollBar                       1406	//(Left Origin = 153, Top Origin = 16, Width = 7, Height = 124, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)
#define LoaditListTable                           1402	//(Left Origin = 0, Top Origin = 16, Width = 152, Height = 124, Editable = 0, Rows = 11)

//	Resource: tFRM 1600
#define RexxletPauseForm                          1600	//(Left Origin = 15, Top Origin = 70, Width = 130, Height = 43, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RexxletPauseDoneButton                    1602	//(Left Origin = 93, Top Origin = 30, Width = 34, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletPauseUnnamed1604BitMap             10004	//(Left Origin = 2, Top Origin = 14, Bitmap Resource ID = 10004, Usable = 1)
#define RexxletPauseReturnCodeField               1601	//(Left Origin = 2, Top Origin = 30, Width = 71, Height = 11, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RexxletPauseUnnamed1603Label              1603	//(Left Origin = 24, Top Origin = 16, Usable = 1, Font = Standard)

//	Resource: tFRM 1700
#define RexxletAlertForm                          1700	//(Left Origin = 3, Top Origin = 102, Width = 154, Height = 55, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RexxletAlertOKButton                      1701	//(Left Origin = 5, Top Origin = 40, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletAlertUnnamed1702BitMap             10007	//(Left Origin = 4, Top Origin = 17, Bitmap Resource ID = 10007, Usable = 1)
#define RexxletAlertMessageField                  1703	//(Left Origin = 23, Top Origin = 14, Width = 130, Height = 24, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Bold, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 62, Top Origin = 139, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed1101BitMap                    3000	//(Left Origin = 4, Top Origin = 15, Bitmap Resource ID = 3000, Usable = 1)
#define AboutUnnamed1107BitMap                    4000	//(Left Origin = 120, Top Origin = 99, Bitmap Resource ID = 4000, Usable = 1)
#define AboutUnnamed1102Label                     1102	//(Left Origin = 74, Top Origin = 29, Usable = 1, Font = Standard)
#define AboutExplanationLabel                     1103	//(Left Origin = 4, Top Origin = 99, Usable = 1, Font = Standard)
#define AboutVersionLabel                         1104	//(Left Origin = 4, Top Origin = 67, Usable = 1, Font = Standard)
#define AboutInfoLabel                            1106	//(Left Origin = 4, Top Origin = 79, Usable = 1, Font = Standard)

//	Resource: tFRM 1200
#define ArgsForm                                  1200	//(Left Origin = 10, Top Origin = 86, Width = 140, Height = 48, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define ArgsRunButton                             1203	//(Left Origin = 6, Top Origin = 32, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ArgsCancelButton                          1204	//(Left Origin = 98, Top Origin = 32, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ArgsArgsField                             1201	//(Left Origin = 37, Top Origin = 15, Width = 100, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 200, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ArgsLabelLabel                            1202	//(Left Origin = 6, Top Origin = 15, Usable = 1, Font = Bold)

//	Resource: tFRM 1300
#define ConsoleForm                               1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1100, Default Button ID = 0)
#define ConsoleDoneButton                         1303	//(Left Origin = 125, Top Origin = 2, Width = 34, Height = 9, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ConsoleIOField                            1301	//(Left Origin = 0, Top Origin = 16, Width = 152, Height = 144, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 10000, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define ConsoleReturnCodeField                    1304	//(Left Origin = 73, Top Origin = 2, Width = 51, Height = 11, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 15, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ConsoleIOScrollBar                        1302	//(Left Origin = 153, Top Origin = 18, Width = 7, Height = 142, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1800
#define RexxletEditForm                           1800	//(Left Origin = 20, Top Origin = 20, Width = 120, Height = 128, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RexxletEditDoneButton                     1803	//(Left Origin = 4, Top Origin = 115, Width = 34, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletEditCancelButton                   1804	//(Left Origin = 75, Top Origin = 115, Width = 34, Height = 11, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletEditEditField                      1801	//(Left Origin = 1, Top Origin = 12, Width = 111, Height = 105, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 1000, Font = Standard, Auto Shift = 1, Has Scroll Bar = 1, Numeric = 0)
#define RexxletEditEditScrollBar                  1802	//(Left Origin = 113, Top Origin = 14, Width = 7, Height = 103, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)

//	Resource: tFRM 1900
#define RexxletURLForm                            1900	//(Left Origin = 10, Top Origin = 86, Width = 140, Height = 48, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define RexxletURLOKButton                        1903	//(Left Origin = 6, Top Origin = 32, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletURLCancelButton                    1904	//(Left Origin = 98, Top Origin = 32, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define RexxletURLURLField                        1901	//(Left Origin = 37, Top Origin = 15, Width = 96, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 200, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define RexxletURLLabelLabel                      1902	//(Left Origin = 6, Top Origin = 15, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define ErrorAlert                                1000
#define ErrorOK                                   0

//	Resource: Talt 1100
#define InformationAlert                          1100
#define InformationOK                             0


//	Resource: MBAR 1000
#define LoadMenuBar                               1000

//	Resource: MBAR 1100
#define ConsoleMenuBar                            1100

//	Resource: MBAR 1200
#define EditMenuBar                               1200


//	Resource: MENU 1100
#define HelpMenu                                  1100
#define HelpAboutRexx                             1100

//	Resource: MENU 1000
#define ConsoleToolsMenu                          1000
#define ConsoleToolsExit                          1000	//  Command Key: T

//	Resource: MENU 1200
#define EditMenu                                  1200
#define EditUndo                                  1200	//  Command Key: U
#define EditCut                                   1201	//  Command Key: X
#define EditCopy                                  1202	//  Command Key: C
#define EditPaste                                 1203	//  Command Key: P
#define EditSelectAll                             1204	//  Command Key: S
#define EditKeyboard                              1206	//  Command Key: K
#define EditGraffitiHelp                          1207	//  Command Key: G

//	Resource: MENU 1300
#define EditToolsMenu                             1300
#define EditToolsRun                              1300	//  Command Key: R
#define EditToolsRunwithargs                      1301	//  Command Key: N
#define EditToolsLoad                             1302	//  Command Key: L
#define EditToolsClear                            1303	//  Command Key: A
#define EditToolsExit                             1305	//  Command Key: T

//	Resource: MENU 1400
#define LoadToolsMenu                             1400
#define LoadToolsRun                              1400	//  Command Key: R
#define LoadToolsRunwithargs                      1401	//  Command Key: N
#define LoadToolsEdit                             1402	//  Command Key: E
#define LoadToolsExit                             1404	//  Command Key: T


//	Resource: tSTR 1000
#define HelpID1000String                          1000	// "This is a Rexx interpreter for Palm OS¨.  It consists of a classic Rexx interpreter with Palm console and database IO, plus a simple IDE (script loader, editor, and launcher).  It also supports the sublaunching of Rexxlets"


//	Resource: tSTL 1400
#define MonthNamesStringList                      1400

//	Resource: tSTL 1300
#define DayNamesStringList                        1300

//	Resource: tSTL 1200
#define RexxBuiltInNamesStringList                1200

//	Resource: tSTL 1100
#define RexxKeywordsStringList                    1100

//	Resource: tSTL 1000
#define RexxMessagesStringList                    1000

//	Resource: tSTL 1500
#define RexxAppMessagesStringList                 1500

//	Resource: tSTL 1600
#define Yasp3MessagesStringList                   1600


//	Resource: PICT 1000
#define BigBWRexxBitmap                           1000

//	Resource: PICT 1100
#define SmallBWRexxBitmap                         1100

//	Resource: PICT 1200
#define BigColorRexxBitmap                        1200

//	Resource: PICT 1300
#define SmallColorRexxBitmap                      1300

//	Resource: PICT 3100
#define BitmapID3100Bitmap                        3100

//	Resource: PICT 3200
#define BitmapID3200Bitmap                        3200

//	Resource: PICT 3000
#define BitmapID3000Bitmap                        3000

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001

//	Resource: PICT 4000
#define BitmapID4000Bitmap                        4000

//	Resource: PICT 4002
#define BitmapID4002Bitmap                        4002

//	Resource: PICT 4003
#define BitmapID4003Bitmap                        4003


//	Resource: tbmf 1000
#define EmblemBitmapFamily                        1000

//	Resource: tbmf 3000
#define BitmapResourceID3000BitmapFamily          3000

//	Resource: tbmf 4000
#define BitmapResourceID4000BitmapFamily          4000


//	Resource: taif 1001
#define SmallEmblemAppIconFamily                  1001

//	Resource: taif 1000
#define BigEmblemAppIconFamily                    1000

