//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 11:56:13 AM on Friday, December 13, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Rexxlets"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 3000
#define AboutForm                                 3000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 3000, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             3005	//(Left Origin = 62, Top Origin = 139, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutUnnamed3001BitMap                    3000	//(Left Origin = 4, Top Origin = 15, Bitmap Resource ID = 3000, Usable = 1)
#define AboutUnnamed3006BitMap                    4000	//(Left Origin = 120, Top Origin = 99, Bitmap Resource ID = 4000, Usable = 1)
#define AboutUnnamed3002Label                     3002	//(Left Origin = 74, Top Origin = 17, Usable = 1, Font = Standard)
#define AboutExplanationLabel                     3003	//(Left Origin = 4, Top Origin = 92, Usable = 1, Font = Standard)
#define AboutVersionLabel                         3004	//(Left Origin = 4, Top Origin = 70, Usable = 1, Font = Standard)

//	Resource: tFRM 2000
#define PreferencesForm                           2000	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 1000, Menu Bar ID = 0, Default Button ID = 2006)
#define PreferencesOKButton                       2006	//(Left Origin = 3, Top Origin = 141, Width = 28, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PreferencesListButton                     2013	//(Left Origin = 37, Top Origin = 141, Width = 28, Height = 12, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PreferencesDefaultsButton                 2014	//(Left Origin = 71, Top Origin = 141, Width = 42, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PreferencesCancelButton                   2046	//(Left Origin = 119, Top Origin = 141, Width = 34, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define PreferencesEnabledCheckbox                2005	//(Left Origin = 0, Top Origin = 69, Width = 150, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define PreferencesCopyPasteCheckbox              2007	//(Left Origin = 0, Top Origin = 114, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define PreferencesPauseCheckbox                  2008	//(Left Origin = 0, Top Origin = 126, Width = 120, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define PreferencesURLField                       2026	//(Left Origin = 28, Top Origin = 84, Width = 126, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 1, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define PreferencesUnnamed2009Label               2009	//(Left Origin = 2, Top Origin = 99, Usable = 1, Font = Bold)
#define PreferencesUnnamed2012Label               2012	//(Left Origin = 2, Top Origin = 39, Usable = 1, Font = Bold)
#define PreferencesUnnamed2015Label               2015	//(Left Origin = 2, Top Origin = 14, Usable = 1, Font = Standard)
#define PreferencesUnnamed2016Label               2016	//(Left Origin = 2, Top Origin = 25, Usable = 1, Font = Standard)
#define PreferencesUnnamed2028Label               2028	//(Left Origin = 68, Top Origin = 39, Usable = 1, Font = Bold)
#define PreferencesUnnamed2029Label               2029	//(Left Origin = 120, Top Origin = 39, Usable = 1, Font = Bold)
#define PreferencesUnnamed2030Label               2030	//(Left Origin = 2, Top Origin = 84, Usable = 1, Font = Bold)
#define PreferencesFromList                       2002	//(Left Origin = 62, Top Origin = 50, Width = 35, Usable = 0, Font = Standard, Visible Items = 4)
#define PreferencesToList                         2004	//(Left Origin = 118, Top Origin = 50, Width = 35, Usable = 0, Font = Standard, Visible Items = 2)
#define PreferencesArgsList                       2011	//(Left Origin = 42, Top Origin = 99, Width = 40, Usable = 0, Font = Standard, Visible Items = 4)
#define PreferencesFromPopTrigger                 2001	//(Left Origin = 53, Top Origin = 50, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2002)
#define PreferencesToPopTrigger                   2003	//(Left Origin = 105, Top Origin = 50, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2004)
#define PreferencesArgsPopTrigger                 2010	//(Left Origin = 29, Top Origin = 99, Width = 45, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 2011)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define ErrorAlert                                1000
#define ErrorOK                                   0


//	Resource: tSTR 3000
#define AboutHelpString                           3000	// "RexxletHack is a system extension ("hack") to support and configure Rexxletsª.  Rexxlets"

//	Resource: tSTR 1000
#define PreferencesHelpString                     1000	// "For each combination of a From/To custom pen stroke, you may specify the source "


//	Resource: PICT 3000
#define BitmapID3000Bitmap                        3000

//	Resource: PICT 3200
#define BitmapID3200Bitmap                        3200

//	Resource: PICT 3100
#define BitmapID3100Bitmap                        3100

//	Resource: PICT 4001
#define BitmapID4001Bitmap                        4001

//	Resource: PICT 4000
#define BitmapID4000Bitmap                        4000

//	Resource: PICT 4002
#define BitmapID4002Bitmap                        4002

//	Resource: PICT 4003
#define BitmapID4003Bitmap                        4003

//	Resource: PICT 1000
#define BigBWRexxBitmap                           1000

//	Resource: PICT 1100
#define SmallBWRexxBitmap                         1100

//	Resource: PICT 1200
#define BigColorRexxBitmap                        1200

//	Resource: PICT 1300
#define SmallColorRexxBitmap                      1300


//	Resource: tbmf 3000
#define BitmapResourceID3000BitmapFamily          3000

//	Resource: tbmf 4000
#define BitmapResourceID4000BitmapFamily          4000


//	Resource: taif 1001
#define SmallEmblemAppIconFamily                  1001

//	Resource: taif 1000
#define BigEmblemAppIconFamily                    1000

